"""初始表结构

Revision ID: 3415add72ad6
Revises: 
Create Date: 2026-05-30 14:08:30.310098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3415add72ad6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户 ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='注册时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='考试 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='考试标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='考试描述'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='考试时长（分钟）'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=1), nullable=False, comment='满分'),
    sa.Column('pass_score', sa.Numeric(precision=5, scale=1), nullable=False, comment='及格分'),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', name='exam_status'), nullable=False, comment='考试状态'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='作答记录 ID'),
    sa.Column('exam_id', sa.Integer(), nullable=False, comment='考试 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='开始时间'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'graded', name='attempt_status'), nullable=False, comment='作答状态'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=1), nullable=True, comment='总分'),
    sa.Column('objective_score', sa.Numeric(precision=5, scale=1), nullable=True, comment='客观题得分'),
    sa.Column('subjective_score', sa.Numeric(precision=5, scale=1), nullable=True, comment='主观题得分'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='题目 ID'),
    sa.Column('exam_id', sa.Integer(), nullable=False, comment='所属考试 ID'),
    sa.Column('type', sa.Enum('single', 'multi', 'judge', 'fill', 'essay', name='question_type'), nullable=False, comment='题型'),
    sa.Column('content', sa.Text(), nullable=False, comment='题目内容'),
    sa.Column('answer', sa.Text(), nullable=False, comment='正确答案'),
    sa.Column('score', sa.Numeric(precision=5, scale=1), nullable=False, comment='分值'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='题目解析'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='选项 ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='所属题目 ID'),
    sa.Column('label', sa.String(length=5), nullable=False, comment='选项标签（A/B/C/D 或 正确/错误）'),
    sa.Column('content', sa.Text(), nullable=False, comment='选项内容'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='是否为正确答案'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='作答 ID'),
    sa.Column('attempt_id', sa.Integer(), nullable=False, comment='作答记录 ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目 ID'),
    sa.Column('user_answer', sa.Text(), nullable=True, comment='用户答案'),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='是否正确'),
    sa.Column('score', sa.Numeric(precision=5, scale=1), nullable=True, comment='得分'),
    sa.Column('graded_by', sa.Enum('auto', 'manual', 'pending', name='graded_by_type'), nullable=False, comment='评分方式'),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_responses')
    op.drop_table('options')
    op.drop_table('questions')
    op.drop_table('exam_attempts')
    op.drop_table('exams')
    op.drop_table('users')
    # ### end Alembic commands ###
